Alien/Predator Universe:
  Movies Missing (TMDb IDs):
    1242898: 'Predator: Badlands (2025)'
Final Destination:
  Movies Missing (TMDb IDs):
    1505252: Final Destination 7
Now You See Me:
  Movies Missing (TMDb IDs):
    1457735: Untitled Now You See Me 4
Rush Hour:
  Movies Missing (TMDb IDs):
    1059776: Rush Hour 4
The Chronicles of Riddick:
  Movies Missing (TMDb IDs):
    374771: 'Riddick: Furya'
Shrek:
  Movies Missing (TMDb IDs):
    421892: Shrek 5 (2027)
Sonic the Hedgehog:
  Movies Missing (TMDb IDs):
    1401586: Sonic the Hedgehog 4 (2027)
Toy Story:
  Movies Missing (TMDb IDs):
    1084244: Toy Story 5 (2026)
How to Train Your Dragon:
  Movies Missing (TMDb IDs):
    1458319: How to Train Your Dragon 2 (2027)
Gladiator:
  Movies Missing (TMDb IDs):
    1359289: Gladiator III
A Quiet Place:
  Movies Missing (TMDb IDs):
    1324923: A Quiet Place Part III (2027)
Scream:
  Movies Missing (TMDb IDs):
    1159559: Scream 7 (2026)
Ice Age:
  Movies Missing (TMDb IDs):
    1384758: 'Ice Age: Boiling Point (2027)'
Tremors:
  Movies Missing (TMDb IDs):
    9362: Tremors (1990)
    11069: 'Tremors 2: Aftershocks (1996)'
    10829: 'Tremors 3: Back to Perfection (2001)'
    10891: 'Tremors 4: The Legend Begins (2004)'
    339530: 'Tremors 5: Bloodlines (2015)'
    496704: 'Tremors: A Cold Day in Hell (2018)'
    670266: 'Tremors: Shrieker Island (2020)'
Blair Witch:
  Movies Missing (TMDb IDs):
    11531: 'Book of Shadows: Blair Witch 2 (2000)'
    351211: Blair Witch (2016)
    1122220: Untitled Blair Witch Film
Frozen:
  Movies Missing (TMDb IDs):
    1024604: Frozen III (2027)
    1205983: Frozen IV
Paddington:
  Movies Missing (TMDb IDs):
    116149: Paddington (2014)
    346648: Paddington 2 (2017)
    516729: Paddington in Peru (2024)
The Secret Life of Pets:
  Movies Missing (TMDb IDs):
    1109206: The Secret Life of Pets 3
Rio:
  Movies Missing (TMDb IDs):
    1523207: Rio 3
Top Gun:
  Movies Missing (TMDb IDs):
    1229934: Untitled Top Gun 3
The Super Mario Bros.:
  Movies Missing (TMDb IDs):
    1226863: The Super Mario Galaxy Movie (2026)
Extraction:
  Movies Missing (TMDb IDs):
    1141700: Extraction 3
James Bond:
  Movies Missing (TMDb IDs):
    1184696: Untitled James Bond Film
Lilo & Stitch:
  Movies Missing (TMDb IDs):
    1504349: Lilo & Stitch 2
47 Meters Down:
  Movies Missing (TMDb IDs):
    1286513: '47 Meters Down: The Wreck'
Cloverfield:
  Movies Missing (TMDb IDs):
    706643: Untitled Cloverfield Sequel
Jumanji:
  Movies Missing (TMDb IDs):
    1260649: Jumanji 3 (2026)
The Fast and the Furious:
  Movies Missing (TMDb IDs):
    755679: 'Fast X: Part 2'
Super Troopers:
  Movies Missing (TMDb IDs):
    675871: 'Super Troopers 3: Winter Soldiers (2026)'
Happy Death Day:
  Movies Missing (TMDb IDs):
    774079: Happy Death Day to Us
Dune:
  Movies Missing (TMDb IDs):
    1170608: 'Dune: Part Three (2026)'
Home Alone:
  Movies Missing (TMDb IDs):
    9714: Home Alone 3 (1997)
    12536: Home Alone 4 (2002)
Silent Hill:
  Movies Missing (TMDb IDs):
    680493: Return to Silent Hill (2026)
Terrifier:
  Movies Missing (TMDb IDs):
    1320786: Terrifier 4 (2026)
Austin Powers:
  Movies Missing (TMDb IDs):
    1565822: Austin Powers 4
Greenland:
  Movies Missing (TMDb IDs):
    840464: 'Greenland 2: Migration (2026)'
Scary Movie:
  Movies Missing (TMDb IDs):
    1273221: Scary Movie (2026)
Mad Max:
  Movies Missing (TMDb IDs):
    340023: 'Mad Max: The Wasteland'
28 ... Later:
  Movies Missing (TMDb IDs):
    1272837: '28 Years Later: The Bone Temple (2026)'
    1273002: 28 Years Later Part 3
Before...:
  Movies Missing (TMDb IDs):
    76: Before Sunrise (1995)
    80: Before Sunset (2004)
    132344: Before Midnight (2013)
The Incredibles:
  Movies Missing (TMDb IDs):
    1327821: Incredibles 3
Honey, I Shrunk the Kids:
  Movies Missing (TMDb IDs):
    9354: Honey, I Shrunk the Kids (1989)
    11158: Honey, I Blew Up the Kid (1992)
    11425: Honey, We Shrunk Ourselves (1997)
Hocus Pocus:
  Movies Missing (TMDb IDs):
    1136067: Hocus Pocus 3
Avatar:
  Movies Missing (TMDb IDs):
    83533: 'Avatar: Fire and Ash (2025)'
    216527: Avatar 4 (2029)
    393209: Avatar 5 (2031)
DC Universe:
  Movies Missing (TMDb IDs):
    1081003: Supergirl (2026)
    1400940: Clayface (2026)
    1080999: The Authority
    1081004: The Brave and the Bold
    1080998: Swamp Thing
    1259816: Teen Titans
    1364797: Dynamic Duo (2028)
    1362897: Untitled Bane and Deathstroke Film
    1504329: Sgt. Rock
    1495964: Untitled Wonder Woman Film
DC Extended Universe:
  Movies Missing (TMDb IDs):
    791373: Zack Snyder's Justice League (2021)
    565770: Blue Beetle (2023)
'Spider-Man: Spider-Verse':
  Movies Missing (TMDb IDs):
    911916: 'Spider-Man: Beyond the Spider-Verse (2027)'
Deadpool:
  Movies Missing (TMDb IDs):
    567604: Once Upon a Deadpool (2018)
Marvel Cinematic Universe:
  Movies Missing (TMDb IDs):
    413279: Team Thor (2016)
    441829: 'Team Thor: Part 2 (2017)'
    505945: Team Darryl (2018)
